version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: faqbuddy_postgres_db
    environment:
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: db_user
      POSTGRES_DB: faqbuddy_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d faqbuddy_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 